# -*- coding: utf-8 -*-
"""reranker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGiN8l118RYuSAeRvC6mnSC-DhmSL3QG
"""

from sentence_transformers import CrossEncoder
import time


RERANKER_MODEL = "BAAI/bge-reranker-base"

# Load once globally ( as it is expensive to reload)
reranker = CrossEncoder(RERANKER_MODEL)


def rerank(query: str, candidates: list[dict], top_k: int = 5) -> list[dict]:
    """
    Rerank retrieved candidates using cross-encoder.

    Args:
        query:      The user's question
        candidates: List of chunks from hybrid_search (top 40)
        top_k:      How many to return after reranking

    Returns:
        top_k chunks sorted by reranker score (highest = most relevant)
    """

    if not candidates:
        return []

    # Build query-document pairs for cross-encoder
    pairs = [
        [query, candidate["text"]]
        for candidate in candidates
    ]

    # Score all pairs — cross-encoder reads both together
    start = time.time()
    scores = reranker.predict(pairs, show_progress_bar=False)
    latency_ms = (time.time() - start) * 1000

    print(f"Reranker scored {len(pairs)} candidates in {latency_ms:.0f}ms")

    # Attach reranker scores to candidates
    for candidate, score in zip(candidates, scores):
        candidate["reranker_score"] = float(score)

    # Sort by reranker score descending
    reranked = sorted(
        candidates,
        key=lambda x: x["reranker_score"],
        reverse=True
    )

    return reranked[:top_k]