# -*- coding: utf-8 -*-
"""chunker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13F1Hif0_X0EPvGMoDXCGO-XgvqpP0jHO
"""

#!pip install -U langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

def chunk_document(doc: dict,
                   chunk_size: int = 512,
                   chunk_overlap: int = 64) -> list[dict]:

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ". ", " "]  # ← ". " instead of "."
    )

    chunks = splitter.split_text(doc["text"])
    chunks = [c for c in chunks if len(c.strip()) > 200]

    # ✅ Fix cut-off starts — skip chunks starting mid-sentence
    clean_chunks = []
    for chunk in chunks:
        stripped = chunk.strip()
        # If starts with lowercase or punctuation, it's mid-sentence
        if stripped and (stripped[0].isupper() or stripped[0].isdigit()):
            clean_chunks.append(chunk)

    return [
        {
            "chunk_id": f"{doc['ticker']}_{doc['date']}_{i}",
            "text": chunk,
            "metadata": {
                "ticker": doc["ticker"],
                "filing_date": doc["date"],
                "chunk_index": i,
                "source": doc["filepath"]
            }
        }
        for i, chunk in enumerate(clean_chunks)
    ]

