# -*- coding: utf-8 -*-
"""edgar_fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZjPp8mKOhO3jnYObRfjI1zmFpjWXSjv
"""

from google.colab import drive
drive.mount('/content/drive')

import requests
import json
import time
from pathlib import Path
HEADERS = {
    "User-Agent": "Yourname yourmail@gmail.com",  # EDGAR requires this
    "Accept-Encoding": "gzip, deflate",
}

def get_company_cik(ticker: str) -> str:
    """Convert ticker symbol to CIK"""
    url = "https://www.sec.gov/files/company_tickers.json"
    response = requests.get(url, headers=HEADERS)
    data = response.json()

    for entry in data.values():
        if entry["ticker"].upper() == ticker.upper():
            # CIK must be zero-padded to 10 digits
            return str(entry["cik_str"]).zfill(10)

    raise ValueError(f"Ticker {ticker} not found")

def get_10k_filings(cik: str, limit: int = 5) -> list[dict]:
    """Get list of 10-K filings for a company"""
    url = f"https://data.sec.gov/submissions/CIK{cik}.json"
    time.sleep(0.1) # Add delay to respect EDGAR rate limit
    response = requests.get(url, headers=HEADERS)
    response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)

    # These debug prints were added to diagnose JSONDecodeError,
    # but the current error is an HTTPError (404), which occurs before these prints.
    # Leaving them for future debugging if JSONDecodeError arises after this fix.
    print(f"DEBUG: Response status code: {response.status_code}")
    print(f"DEBUG: Response headers: {response.headers}")
    print(f"DEBUG: Raw response text (first 500 chars):\n{response.text[:500]}")

    data = response.json()

    filings = data["filings"]["recent"]
    results = []

    for i, form_type in enumerate(filings["form"]):
        if form_type == "10-K":
            results.append({
                "accession_number": filings["accessionNumber"][i],
                "filing_date": filings["filingDate"][i],
                "primary_document": filings["primaryDocument"][i],
            })
        if len(results) >= limit:
            break

    return results

def download_10k(cik: str, accession_number: str,
                 primary_doc: str, save_dir: str = "/content/drive/MyDrive/sec-rag-system/data/raw") -> Path:
    """Download actual 10-K document"""

    # Format accession number for URL
    acc_formatted = accession_number.replace("-", "")

    url = (
        f"https://www.sec.gov/Archives/edgar/data/"
        f"{int(cik)}/{acc_formatted}/{primary_doc}"
    )

    response = requests.get(url, headers=HEADERS)

    # Save file
    save_path = Path(save_dir)
    save_path.mkdir(parents=True, exist_ok=True)

    filename = f"{cik}_{accession_number}.html"
    filepath = save_path / filename
    filepath.write_bytes(response.content)
    print(f"Saved to {filepath}")
    time.sleep(0.1)  # EDGAR rate limit: max 10 requests/sec

    return filepath

def fetch_company_filings(ticker: str, limit: int = 3):
    """Main function — fetch last N 10-Ks for a ticker"""
    print(f"Fetching filings for {ticker}...")

    cik = get_company_cik(ticker)
    print(f"CIK: {cik}")

    filings = get_10k_filings(cik, limit=limit)
    print(f"Found {len(filings)} 10-K filings")

    downloaded = []
    for filing in filings:
        path = download_10k(
            cik,
            filing["accession_number"],
            filing["primary_document"]
        )
        downloaded.append({
            "ticker": ticker,
            "date": filing["filing_date"],
            "path": str(path)
        })
        print(f"Downloaded: {filing['filing_date']} → {path}")

    return downloaded