# -*- coding: utf-8 -*-
"""parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRyZeBCjvB1h3ggwbpvaoEB8JQ6S85FM
"""

from bs4 import BeautifulSoup
from pathlib import Path
import re

def format_ixbrl_value(tag) -> str:
    """Convert raw iXBRL number to human readable format"""
    raw = tag.get_text(strip=True).replace(",", "").strip()
    if not raw:
        return ""
    try:
        value = float(raw)
        scale = int(tag.get("scale", 0))
        unitref = tag.get("unitref", "").lower()
        value = value * (10 ** scale)

        if "usd" in unitref:
            if abs(value) >= 1_000_000_000:
                return f"${value/1_000_000_000:.1f}B"
            elif abs(value) >= 1_000_000:
                return f"${value/1_000_000:.1f}M"
            else:
                return f"${value:,.0f}"
        elif "shares" in unitref:
            if abs(value) >= 1_000_000_000:
                return f"{value/1_000_000_000:.2f}B shares"
            elif abs(value) >= 1_000_000:
                return f"{value/1_000_000:.1f}M shares"
            else:
                return f"{value:,.0f} shares"
        else:
            if abs(value) >= 1_000_000_000:
                return f"{value/1_000_000_000:.1f}B"
            elif abs(value) >= 1_000_000:
                return f"{value/1_000_000:.1f}M"
            else:
                return f"{value:,.2f}"
    except (ValueError, TypeError):
        return tag.get_text(strip=True)


def parse_10k_html(filepath: str) -> dict:
    content = Path(filepath).read_bytes()
    soup = BeautifulSoup(content, "html.parser")

    # ── Step 1: Remove XBRL metadata ─────────────────────────────
    for tag in soup.find_all(["ix:header", "xbrli:xbrl",
                               "xbrli:context", "xbrli:unit",
                               "script", "style"]):
        tag.decompose()

    # ── Step 2: Replace ix:nonfraction with formatted numbers ────
    # Do this BEFORE table extraction so cells get proper values
    for tag in soup.find_all(re.compile(r"^ix:nonfraction")):
        formatted = format_ixbrl_value(tag)
        tag.replace_with(formatted if formatted else "")

    # ── Step 3: Unwrap remaining ix: wrapper tags ─────────────────
    for tag in soup.find_all(re.compile(r"^ix:")):
        tag.unwrap()

    # ── Step 4: Extract tables with scale context ─────────────────
    for table in soup.find_all("table"):

        prev_text = ""
        for sibling in table.previous_siblings:
            t = getattr(sibling, "get_text", lambda: str(sibling))()
            if t.strip():
                prev_text = t.strip().lower()
                break

        full_context = (table.get_text(" ", strip=True) + " " + prev_text).lower()

        if "in millions" in full_context:
            scale_note = "[figures in millions USD]"
        elif "in billions" in full_context:
            scale_note = "[figures in billions USD]"
        else:
            scale_note = ""

        rows = []
        for row in table.find_all("tr"):
            cells = [
                c.get_text(" ", strip=True)
                for c in row.find_all(["td", "th"])
            ]
            # Lower threshold — keep rows with ANY dollar amount
            non_empty = [c for c in cells if c and len(c) > 0]
            has_value = any("$" in c or c.replace(",","").replace(".","").isdigit()
                          for c in non_empty)

            if len(non_empty) >= 2 or (non_empty and has_value):
                rows.append(" | ".join(non_empty))

        if rows:
            header = f"{scale_note}\n" if scale_note else ""
            table.replace_with("\n" + header + "\n".join(rows) + "\n")
        else:
            table.decompose()

    # ── Step 5: Get clean text ────────────────────────────────────
    text = soup.get_text(separator="\n")
    lines = [l.strip() for l in text.splitlines()]

    clean_lines = []
    clean_lines = []
    for line in lines:
        # Skip XBRL artifacts
        if any(x in line for x in [
            "iso4217", "xbrli", "aapl:", "xbrldi",
            "P1Y", "P3Y", "false", "true"
        ]):
            continue
        # Skip orphaned $ signs
        if line.strip() in ["$", "$$", ""]:
            continue
        # Skip page headers
        if re.match(r"^Apple Inc\.\s*\|.*10-K\s*\|\s*\d+$", line):
            continue

        # Keep lines with dollar amounts even if short
        has_dollar = "$" in line and ("B" in line or "M" in line)
        has_table = "|" in line and "$" in line
        long_enough = len(line) > 80

        if long_enough or has_dollar or has_table:
            clean_lines.append(line)

    clean_text = "\n".join(clean_lines)

    return {
        "filepath": filepath,
        "text": clean_text,
        "char_count": len(clean_text)
    }