# -*- coding: utf-8 -*-
"""tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0FrOYC06V_IXQiOXtPfeGbG0a4aloaS
"""

import time,datetime
import json
import os
from datetime import datetime
from pathlib import Path
from collections import defaultdict
import numpy as np

LOG_PATH = "data/observability_log.jsonl"
Path("data").mkdir(exist_ok=True)


class RAGTracker:
    """
    Tracks latency, cost and quality for every RAG query.
    Logs to JSONL file — one record per query.
    """

    # Groq llama-3.1-8b pricing (per million tokens)
    COST_PER_1M_INPUT  = 0.05   # $0.05 per 1M input tokens
    COST_PER_1M_OUTPUT = 0.08   # $0.08 per 1M output tokens

    def __init__(self):
        self.current = {}       # active query being tracked
        self.history = []       # all completed queries this session

    # ── Timing ───────────────────────────────────────────────────

    def start_query(self, query: str):
        """Call at start of every query"""
        self.current = {
            "query": query,
            "timestamp": datetime.utcnow().isoformat(),
            "stages": {},
            "metrics": {}
        }

    def start_stage(self, stage: str):
        """Call before each pipeline stage"""
        self.current["stages"][stage] = {"start": time.perf_counter()}

    def end_stage(self, stage: str):
        """Call after each pipeline stage"""
        elapsed = (
            time.perf_counter() -
            self.current["stages"][stage]["start"]
        ) * 1000  # ms
        self.current["stages"][stage]["latency_ms"] = round(elapsed, 2)
        return elapsed

    # ── Quality Metrics ───────────────────────────────────────────

    def record_retrieval(self, vector_hits: int, bm25_hits: int,
                         candidates: int):
        self.current["metrics"].update({
            "vector_hits": vector_hits,
            "bm25_hits": bm25_hits,
            "rrf_candidates": candidates
        })

    def record_reranking(self, reranker_scores: list[float],
                         threshold: float):
        passed = [s for s in reranker_scores if s >= threshold]
        self.current["metrics"].update({
            "reranker_top_score": round(max(reranker_scores), 4),
            "reranker_avg_score": round(np.mean(reranker_scores), 4),
            "chunks_passed_threshold": len(passed),
            "chunks_filtered": len(reranker_scores) - len(passed)
        })

    def record_generation(self, tokens_used: int, citations: list,
                          answer: str, input_tokens: int = 0,
                          output_tokens: int = 0):

        # Cost calculation
        cost_usd = (
            (input_tokens  / 1_000_000) * self.COST_PER_1M_INPUT +
            (output_tokens / 1_000_000) * self.COST_PER_1M_OUTPUT
        )

        # Quality signals
        refused = "not available in the provided filings" in answer.lower()
        citation_rate = len(citations) / max(
            len(answer.split("\n")), 1
        )

        self.current["metrics"].update({
            "tokens_total": tokens_used,
            "tokens_input": input_tokens,
            "tokens_output": output_tokens,
            "cost_usd": round(cost_usd, 6),
            "citations_count": len(citations),
            "citation_rate": round(citation_rate, 3),
            "answer_refused": refused,
            "answer_length_chars": len(answer)
        })

    # ── Finalize ──────────────────────────────────────────────────

    def finish_query(self) -> dict:
        """Call at end of query — saves record and returns it"""

        # Total end-to-end latency
        total_ms = sum(
            v.get("latency_ms", 0)
            for v in self.current["stages"].values()
        )
        self.current["total_latency_ms"] = round(total_ms, 2)

        # Save to history
        self.history.append(self.current.copy())

        # Append to JSONL log
        with open(LOG_PATH, "a") as f:
            f.write(json.dumps(self.current) + "\n")

        return self.current

    # ── Analytics ─────────────────────────────────────────────────

    def summary(self):
        """Print p50/p95 latency and cost stats across all queries"""
        if not self.history:
            print("No queries recorded yet.")
            return

        total_latencies = [q["total_latency_ms"] for q in self.history]
        stage_latencies  = defaultdict(list)

        for q in self.history:
            for stage, data in q["stages"].items():
                if "latency_ms" in data:
                    stage_latencies[stage].append(data["latency_ms"])

        total_cost = sum(
            q["metrics"].get("cost_usd", 0) for q in self.history
        )
        refusals = sum(
            1 for q in self.history
            if q["metrics"].get("answer_refused", False)
        )

        print(f"\n{'='*55}")
        print(f"  OBSERVABILITY SUMMARY — {len(self.history)} queries")
        print(f"{'='*55}")

        print(f"\n📊 END-TO-END LATENCY")
        print(f"  p50 : {np.percentile(total_latencies, 50):.0f}ms")
        print(f"  p95 : {np.percentile(total_latencies, 95):.0f}ms")
        print(f"  max : {max(total_latencies):.0f}ms")

        print(f"\n⏱  LATENCY BY STAGE")
        for stage, lats in stage_latencies.items():
            print(f"  {stage:<20} "
                  f"p50={np.percentile(lats,50):.0f}ms  "
                  f"p95={np.percentile(lats,95):.0f}ms")

        print(f"\n💰 COST")
        print(f"  Total cost     : ${total_cost:.6f}")
        print(f"  Avg per query  : ${total_cost/len(self.history):.6f}")

        print(f"\n✅ QUALITY")
        avg_citations = np.mean([
            q["metrics"].get("citations_count", 0)
            for q in self.history
        ])
        avg_score = np.mean([
            q["metrics"].get("reranker_top_score", 0)
            for q in self.history
        ])
        print(f"  Avg citations/query : {avg_citations:.1f}")
        print(f"  Avg top rerank score: {avg_score:.3f}")
        print(f"  Refusal rate        : "
              f"{refusals}/{len(self.history)} queries")
        print(f"{'='*55}\n")