# -*- coding: utf-8 -*-
"""gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOyLPgsztiJvZ8JNwdD0uW4MQPrOaWfw
"""

import gradio as gr
import time
import re
import numpy as np

# ── Pipeline imports ──────────────────────────────────────────
from retrieval.vector_store import vector_search
from retrieval.bm25_retriever import BM25Retriever
from retrieval.hybrid_retriever import reciprocal_rank_fusion
from reranking.reranker import rerank
from generation.generator import generate_answer

# ── Load BM25 index once at startup ──────────────────────────
bm25 = BM25Retriever()
bm25.load_index()
print("BM25 index loaded")

def run_rag(query, top_k, rerank_k, threshold):
    """Main pipeline function — called by Gradio"""

    if not query.strip():
        return "Please enter a question.", "", "", ""

    t_start = time.perf_counter()

    # Stage 1: Retrieval
    t0 = time.perf_counter()
    vec_results  = vector_search(query, top_k=int(top_k))
    bm25_results = bm25.search(query, top_k=int(top_k))
    merged       = reciprocal_rank_fusion([vec_results, bm25_results])
    candidates   = merged[:40]
    retrieval_ms = (time.perf_counter() - t0) * 1000

    # Stage 2: Reranking
    t0 = time.perf_counter()
    reranked     = rerank(query, candidates, top_k=int(rerank_k))
    reranking_ms = (time.perf_counter() - t0) * 1000

    # Stage 3: Generation
    t0 = time.perf_counter()
    result       = generate_answer(query, reranked,
                                   score_threshold=threshold)
    generation_ms = (time.perf_counter() - t0) * 1000
    total_ms      = (time.perf_counter() - t_start) * 1000

    # ── Format answer ─────────────────────────────────────────
    answer = result["answer"]

    # ── Format metrics ────────────────────────────────────────
    metrics = f"""
⏱️  LATENCY
  Retrieval:   {retrieval_ms:.0f}ms
  Reranking:   {reranking_ms:.0f}ms
  Generation:  {generation_ms:.0f}ms
  Total:       {total_ms:.0f}ms

💰 COST
  Tokens used: {result['tokens_used']}
  Est. cost:   ${result['tokens_used'] * 0.00000005:.6f}

✅ QUALITY
  Sources used:    {result['sources_used']}
  Chunks filtered: {result['chunks_filtered']}
  Citations:       {len(result['citations_in_answer'])}
"""

    # ── Format citations ──────────────────────────────────────
    if result["citations_in_answer"]:
        citations = "\n".join(
            f"• {c}" for c in result["citations_in_answer"]
        )
    else:
        citations = "No citations — answer refused or no relevant chunks found."

    # ── Format chunks ─────────────────────────────────────────
    chunks_text = ""
    for i, chunk in enumerate(reranked):
        score = chunk.get("reranker_score", 0)
        meta  = chunk.get("metadata", {})
        chunks_text += (
            f"[Chunk {i+1}] "
            f"Score: {score:.4f} | "
            f"{meta.get('ticker')} {meta.get('filing_date')} | "
            f"chunk {meta.get('chunk_index')}\n"
            f"{chunk['text'][:300]}\n"
            f"{'─'*60}\n"
        )

    return answer, metrics, citations, chunks_text


# ── Build Gradio UI ───────────────────────────────────────────
with gr.Blocks(title="SEC Filing RAG", theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # 📊 SEC Filing RAG System
    **Production RAG over Apple 10-K filings**
    Hybrid retrieval · Cross-encoder reranking · Citation enforcement
    """)

    with gr.Row():

        # ── Left column — inputs ──────────────────────────────
        with gr.Column(scale=1):
            gr.Markdown("### ⚙️ Settings")
            top_k     = gr.Slider(10, 30, value=20, step=1,
                                  label="Retrieval top-k")
            rerank_k  = gr.Slider(3,  10, value=5,  step=1,
                                  label="Rerank top-k")
            threshold = gr.Slider(0.05, 0.30, value=0.10, step=0.01,
                                  label="Score threshold")

            gr.Markdown("### 💡 Example Queries")
            examples = gr.Examples(
                examples=[
                    ["What are Apple's main risk factors?"],
                    ["What were Apple total net sales in 2025?"],
                    ["What were Apple's operating expenses in 2025?"],
                    ["What were iPhone net sales in 2025?"],
                    ["What regulatory risks does Apple face globally?"],
                    ["What is Apple's plan to acquire Tesla?"],
                ],
                inputs=[],  # filled below
                label=""
            )

        # ── Right column — query + output ─────────────────────
        with gr.Column(scale=2):
            query_box = gr.Textbox(
                label="Ask a question about Apple's SEC filings:",
                placeholder="e.g. What are Apple's main risk factors?",
                lines=2
            )
            ask_btn = gr.Button("🔍 Ask", variant="primary")

            gr.Markdown("### 📝 Answer")
            answer_box = gr.Textbox(
                label="", lines=10, interactive=False
            )

            with gr.Row():
                with gr.Column():
                    gr.Markdown("### 📊 Metrics")
                    metrics_box = gr.Textbox(
                        label="", lines=12, interactive=False
                    )
                with gr.Column():
                    gr.Markdown("### 🔗 Citations")
                    citations_box = gr.Textbox(
                        label="", lines=12, interactive=False
                    )

            gr.Markdown("### 🔍 Retrieved Chunks")
            chunks_box = gr.Textbox(
                label="", lines=15, interactive=False
            )

    # Wire examples to query box
    examples = gr.Examples(
        examples=[
            ["What are Apple's main risk factors?"],
            ["What were Apple total net sales in 2025?"],
            ["What were Apple's operating expenses in 2025?"],
            ["What were iPhone net sales in 2025?"],
            ["What regulatory risks does Apple face globally?"],
            ["What is Apple's plan to acquire Tesla?"],
        ],
        inputs=query_box,
        label="Click any example to load it"
    )

    # Wire button
    ask_btn.click(
        fn=run_rag,
        inputs=[query_box, top_k, rerank_k, threshold],
        outputs=[answer_box, metrics_box, citations_box, chunks_box]
    )

    # Also trigger on Enter
    query_box.submit(
        fn=run_rag,
        inputs=[query_box, top_k, rerank_k, threshold],
        outputs=[answer_box, metrics_box, citations_box, chunks_box]
    )

# ── Launch ────────────────────────────────────────────────────
demo.launch(share=True)  # share=True gives you a public URL instantly