# -*- coding: utf-8 -*-
"""bm25_retriever.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSMq5_tAEGAMJ4znQXhZAfHQ-ZdL-lpB
"""

#!pip install qdrant-client sentence-transformers rank-bm25 langchain openai python-dotenv

from rank_bm25 import BM25Okapi
import json
from pathlib import Path
import pickle

BM25_INDEX_PATH = "/content/drive/MyDrive/sec-rag-system/data/bm25_index.pkl"


class BM25Retriever:
    def __init__(self):
        self.bm25 = None
        self.chunks = []

    def build_index(self, chunks: list[dict]):
        """Build BM25 index from chunks"""
        self.chunks = chunks

        # Tokenize (simple whitespace split — good enough for financial text)
        tokenized = [
            chunk["text"].lower().split()
            for chunk in chunks
        ]

        self.bm25 = BM25Okapi(tokenized)

        # Save index to disk
        Path("data").mkdir(exist_ok=True)
        with open(BM25_INDEX_PATH, "wb") as f:
            pickle.dump({
                "bm25": self.bm25,
                "chunks": self.chunks
            }, f)

        print(f"BM25 index built with {len(chunks)} chunks")

    def load_index(self):
        """Load existing BM25 index from disk"""
        with open(BM25_INDEX_PATH, "rb") as f:
            data = pickle.load(f)
        self.bm25 = data["bm25"]
        self.chunks = data["chunks"]
        print("BM25 index loaded")

    def search(self, query: str, top_k: int = 20) -> list[dict]:
        """Keyword search"""
        tokenized_query = query.lower().split()
        scores = self.bm25.get_scores(tokenized_query)

        # Get top_k indices
        top_indices = sorted(
            range(len(scores)),
            key=lambda i: scores[i],
            reverse=True
        )[:top_k]

        return [
            {
                "text": self.chunks[i]["text"],
                "metadata": self.chunks[i]["metadata"],
                "score": float(scores[i]),
                "source": "bm25"
            }
            for i in top_indices
            if scores[i] > 0  # skip zero-score results
        ]

