# -*- coding: utf-8 -*-
"""hybrid_retriever.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qbe82wcXaqsCm4bmc9VsJIMhkL7u6GPt
"""

from google.colab import drive
drive.mount('/content/drive')

from retrieval.vector_store import vector_search
from retrieval.bm25_retriever import BM25Retriever

def reciprocal_rank_fusion(
    result_lists: list[list[dict]],
    k: int = 60
) -> list[dict]:
    scores = {}
    chunk_map = {}

    for result_list in result_lists:
        for rank, result in enumerate(result_list):
            doc_id = result["text"][:100]
            if doc_id not in scores:
                scores[doc_id] = 0
                chunk_map[doc_id] = result
            scores[doc_id] += 1 / (k + rank + 1)

    sorted_ids = sorted(scores, key=lambda x: scores[x], reverse=True)
    return [
        {**chunk_map[doc_id], "rrf_score": scores[doc_id]}
        for doc_id in sorted_ids
    ]


def hybrid_search(
    query: str,
    bm25_retriever: BM25Retriever,
    top_k: int = 20,
    final_k: int = 40,
    rerank_top_k: int = 5          # ← new parameter
) -> list[dict]:
    """
    Full pipeline:
    BM25 + Vector → RRF merge → Cross-Encoder Rerank
    """

    # Stage 1: Retrieve candidates from both retrievers
    vector_results = vector_search(query, top_k=top_k)
    bm25_results = bm25_retriever.search(query, top_k=top_k)

    print(f"Vector hits: {len(vector_results)} | BM25 hits: {len(bm25_results)}")

    # Stage 2: Merge with RRF
    merged = reciprocal_rank_fusion([vector_results, bm25_results])
    candidates = merged[:final_k]

    print(f"RRF merged: {len(candidates)} candidates → reranking...")

    # Stage 3: Rerank — this is the new step
    reranked = rerank(query, candidates, top_k=rerank_top_k)

    return reranked

