# -*- coding: utf-8 -*-
"""rag_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NV30VNKS0jw_NTwqzo5hPCHskWNbB-M
"""

import time

# ── Ingestion ─────────────────────────────────────────────────
from ingestion.edgar_fetcher import fetch_company_filings
from ingestion.parser import parse_10k_html
from ingestion.chunker import chunk_document

# ── Retrieval ─────────────────────────────────────────────────
from retrieval.vector_store import create_collection, embed_and_store, vector_search
from retrieval.bm25_retriever import BM25Retriever
from retrieval.hybrid_retriever import reciprocal_rank_fusion

# ── Reranking ─────────────────────────────────────────────────
from reranking.reranker import rerank

# ── Generation ────────────────────────────────────────────────
from generation.generator import generate_answer

# ── Observability ─────────────────────────────────────────────
from observability.tracker import RAGTracker

# ── Global tracker ────────────────────────────────────────────
tracker = RAGTracker()

def ask(
    query: str,
    bm25_retriever,
    top_k: int = 20,
    rerank_top_k: int = 5,
    score_threshold: float = 0.10,
    verbose: bool = True
) -> dict:

    tracker.start_query(query)

    # ── Stage 1: Retrieval ────────────────────────────────────
    tracker.start_stage("retrieval")
    vector_results = vector_search(query, top_k=top_k)
    bm25_results   = bm25_retriever.search(query, top_k=top_k)
    merged         = reciprocal_rank_fusion([vector_results, bm25_results])
    candidates     = merged[:40]
    tracker.end_stage("retrieval")

    tracker.record_retrieval(
        vector_hits=len(vector_results),
        bm25_hits=len(bm25_results),
        candidates=len(candidates)
    )

    # ── Stage 2: Reranking ────────────────────────────────────
    tracker.start_stage("reranking")
    reranked = rerank(query, candidates, top_k=rerank_top_k)
    tracker.end_stage("reranking")

    tracker.record_reranking(
        reranker_scores=[r["reranker_score"] for r in reranked],
        threshold=score_threshold
    )

    # ── Stage 3: Generation ───────────────────────────────────
    tracker.start_stage("generation")
    result = generate_answer(
        query=query,
        reranked_chunks=reranked,
        score_threshold=score_threshold
    )
    tracker.end_stage("generation")

    tracker.record_generation(
        tokens_used=result["tokens_used"],
        citations=result["citations_in_answer"],
        answer=result["answer"],
        input_tokens=result.get("input_tokens", 0),
        output_tokens=result.get("output_tokens", 0)
    )

    record = tracker.finish_query()

    if verbose:
        print(f"\n{'='*55}")
        print(f"Query: {query}")
        print(f"{'='*55}")
        print(f"Latency  → "
              f"retrieval: {record['stages']['retrieval']['latency_ms']:.0f}ms | "
              f"reranking: {record['stages']['reranking']['latency_ms']:.0f}ms | "
              f"generation: {record['stages']['generation']['latency_ms']:.0f}ms")
        print(f"Total    → {record['total_latency_ms']:.0f}ms")
        print(f"Cost     → ${record['metrics']['cost_usd']:.6f}")
        print(f"Citations→ {record['metrics']['citations_count']}")
        print(f"\nANSWER:\n{result['answer']}")

    return {**result, "record": record}

def main(ticker="AAPL", limit=1):
    print(f"Starting pipeline for {ticker}...")

    filings = fetch_company_filings(ticker, limit=limit)
    parsed  = [parse_10k_html(f["path"]) for f in filings]

    for i, doc in enumerate(parsed):
        doc["ticker"] = filings[i]["ticker"]
        doc["date"]   = filings[i]["date"]

    all_chunks = []
    for doc in parsed:
        all_chunks.extend(chunk_document(doc))

    print(f"Total chunks: {len(all_chunks)}")

    create_collection()
    embed_and_store(all_chunks)

    bm25 = BM25Retriever()
    bm25.build_index(all_chunks)

    print("Pipeline complete!")
    return bm25


if __name__ == "__main__":
    main()

#test cases
tracker = RAGTracker()
bm25 = BM25Retriever()
bm25.load_index()

DEMO_QUERIES = [
    "What are Apple's main risk factors?",
    "What were Apple total net sales in 2025?",
    "What were Apple's operating expenses in 2025?",
    "What is Apple's plan to acquire Tesla?",
    "What were iPhone net sales in 2025?",
    "What regulatory risks does Apple face globally?",
]

for q in DEMO_QUERIES:
    ask(query=q, bm25_retriever=bm25, verbose=True)
    time.sleep(3)

tracker.summary()