# -*- coding: utf-8 -*-
"""vector_store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rnd6Ftqfm1o25SDCD4zWbfupz62N-4jx
"""

#!pip install qdrant-client sentence-transformers rank-bm25 langchain openai python-dotenv

from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance, VectorParams, PointStruct
)
from sentence_transformers import SentenceTransformer
from pathlib import Path
import uuid

from google.colab import drive
drive.mount('/content/drive')

# Using local Qdrant (no server needed for dev)
# Switch to cloud Qdrant for production
client = QdrantClient(path="/content/drive/MyDrive/sec-rag-system/data/qdrant_db")

COLLECTION_NAME = "sec_filings"
EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"  # Fast, free, good quality

embedder = SentenceTransformer(EMBEDDING_MODEL)

def create_collection():
    """Create Qdrant collection if it doesn't exist"""
    existing = [c.name for c in client.get_collections().collections]

    if COLLECTION_NAME not in existing:
        client.create_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(
                size=384,        # BGE-small output dim
                distance=Distance.COSINE
            )
        )
        print(f"Collection '{COLLECTION_NAME}' created")
    else:
        print(f"Collection '{COLLECTION_NAME}' already exists")

def embed_and_store(chunks: list[dict]):
    """Embed chunks and store in Qdrant"""

    texts = [chunk["text"] for chunk in chunks]

    print(f"Embedding {len(texts)} chunks...")
    embeddings = embedder.encode(
        texts,
        batch_size=32,
        show_progress_bar=True,
        normalize_embeddings=True  # Important for cosine similarity
    )

    points = [
        PointStruct(
            id=str(uuid.uuid4()),
            vector=embedding.tolist(),
            payload={
                "text": chunk["text"],
                **chunk["metadata"]
            }
        )
        for chunk, embedding in zip(chunks, embeddings)
    ]

    # Upload in batches
    batch_size = 100
    for i in range(0, len(points), batch_size):
        batch = points[i:i + batch_size]
        client.upsert(
            collection_name=COLLECTION_NAME,
            points=batch
        )

    print(f"Stored {len(points)} chunks in Qdrant")

def vector_search(query: str, top_k: int = 20) -> list[dict]:
    """Semantic search over stored chunks"""

    query_embedding = embedder.encode(
        query,
        normalize_embeddings=True
    ).tolist()

    results = client.search(
        collection_name=COLLECTION_NAME,
        query_vector=query_embedding,
        limit=top_k,
        with_payload=True
    )

    return [
        {
            "text": r.payload["text"],
            "metadata": {k: v for k, v in r.payload.items() if k != "text"},
            "score": r.score,
            "source": "vectordef vector_search(query: str, top_k: int = 20) -> list[dict]:
    """Semantic search over stored chunks"""

    query_embedding = embedder.encode(
        query,
        normalize_embeddings=True
    ).tolist()


    results = client.query_points(
        collection_name=COLLECTION_NAME,
        query=query_embedding,
        limit=top_k,
        with_payload=True
    ).points

    return [
        {
            "text": r.payload["text"],
            "metadata": {k: v for k, v in r.payload.items() if k != "text"},
            "score": r.score,
            "source": "vector"
        }
        for r in results
    ]"
        }
        for r in results
    ]

