# -*- coding: utf-8 -*-
"""generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6rCIDamzCdMztWRbbICWdWuYZ5S0h_a
"""

import os
import re
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client_llm = Groq(api_key="api_key")

SYSTEM_PROMPT = """You are a financial analyst assistant that answers
questions about SEC filings and earnings data.

STRICT RULES:
1. Answer ONLY using the provided context chunks
2. Every factual claim MUST include a citation in format [Source: TICKER 10-K DATE, chunk N]
3. If the answer is not in the context, say "This information is not available in the provided filings"
4. Never hallucinate numbers, dates, or facts not present in context
5. When multiple chunks support a claim, cite all of them
6. Structure your answer clearly with most important facts first

Citation format: [Source: AAPL 10-K 2025-10-31, chunk 12]"""


def format_context(reranked_chunks: list[dict]) -> str:
    context_parts = []
    for i, chunk in enumerate(reranked_chunks):
        meta = chunk.get("metadata", {})
        ticker = meta.get("ticker", "UNKNOWN")
        date = meta.get("filing_date", "UNKNOWN")
        chunk_idx = meta.get("chunk_index", i)

        context_parts.append(
            f"[Chunk {i+1}] Source: {ticker} 10-K {date}, chunk {chunk_idx}\n"
            f"{chunk['text']}\n"
        )
    return "\n---\n".join(context_parts)


def generate_answer(
    query: str,
    reranked_chunks: list[dict],
    score_threshold: float = 0.15,
    model: str = "llama-3.1-8b-instant"   # ← Groq model
) -> dict:

    # Filter low confidence chunks
    filtered = [
        c for c in reranked_chunks
        if c.get("reranker_score", 1.0) >= score_threshold
    ]

    if not filtered:
        return {
            "answer": "No sufficiently relevant information found in the filings.",
            "sources_used": 0,
            "chunks_filtered": len(reranked_chunks),
            "citations_in_answer": [],
            "tokens_used": 0
        }

    print(f"Using {len(filtered)}/{len(reranked_chunks)} chunks "
          f"(threshold: {score_threshold})")

    context = format_context(filtered)

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "user",
            "content": f"""Answer this question using ONLY the context below.

Question: {query}

Context:
{context}

Remember: cite every factual claim using [Source: TICKER 10-K DATE, chunk N] format."""
        }
    ]

    response = client_llm.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0.0,
        max_tokens=1000
    )

    answer = response.choices[0].message.content
    cited_chunks = re.findall(r"\[Source:.*?\]", answer)

    return {
        "answer": answer,
        "sources_used": len(filtered),
        "chunks_filtered": len(reranked_chunks) - len(filtered),
        "citations_in_answer": cited_chunks,
        "tokens_used": response.usage.total_tokens,
        "input_tokens": response.usage.prompt_tokens,
        "output_tokens": response.usage.completion_tokens
    }
 ### #Start with llama-3.1-8b-instant for testing, switch to llama-3.3-70b-versatile for final demo.